# main text of home
name: André Vitor Valle
bio: "Hi, I'm a developer from Rio de Janeiro, Brasil."

# if it's an external image, update below for true
external-image: true
picture: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/1/005/0ae/37d/2472e69.jpg'

url: http://andrevvalle.github.io

permalink: /Software Developer/Web Javascript from Rio de Janeiro./

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-51322118-1'

# if you don't want comments in your posts, set to false
disqus: andrevvalle

# if you don't have any of social below, comment the line
facebook: andrevvalle
twitter: andrevalle1
instagram: andrevvalle
linkedin: in/andrevvalle
github: andrevvalle
email: hi[@]andre[dot]ooo
# google: mygoogle
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# medium: medium

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
